### ISSUE TITLE
docker build failed on version conflict

### ISSUE THREAD

**Issue by rcemper** [grongierisc/iris-pero-ocr#1]
#11 69.31 Collecting typing-extensions
#11 69.34   Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)
#11 69.40 INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version i
 compatible with other requirements. This could take a while.
#11 69.40 INFO: pip is looking at multiple versions of torch to determine which version is compatible with other
equirements. This could take a while.
#11 69.41 ERROR: Cannot install -r requirements.txt (line 4) and torch==1.13.0+cpu because these package versions
have conflicting dependencies.
#11 69.41
#11 69.41 The conflict is caused by:
#11 69.41     The user requested torch==1.13.0+cpu
#11 69.41     torchvision 0.13.0+cpu depends on torch==1.12.0
#11 69.41
#11 69.41 To fix this you could try to:
#11 69.41 1. loosen the range of package versions you've specified
#11 69.41 2. remove package versions to allow pip attempt to solve the dependency conflict
#11 69.41
#11 69.41 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/
dealing-with-dependency-conflicts
#11 ERROR: executor failed running [/bin/sh -c pip3 install -r requirements.txt]: exit code: 1
------
 > [7/8] RUN pip3 install -r requirements.txt:
#11 69.41
#11 69.41 The conflict is caused by:
#11 69.41     The user requested torch==1.13.0+cpu
#11 69.41     torchvision 0.13.0+cpu depends on torch==1.12.0
#11 69.41
#11 69.41 To fix this you could try to:
#11 69.41 1. loosen the range of package versions you've specified
#11 69.41 2. remove package versions to allow pip attempt to solve the dependency conflict
#11 69.41
#11 69.41 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/
dealing-with-dependency-conflicts
------
failed to solve: executor failed running [/bin/sh -c pip3 install -r requirements.txt]: exit code: 1

**Comment by grongierisc** [comment]
This commit should fix the dependency issue with newer version of IRIS/Ubuntu

**Comment by rcemper** [comment]
thanks that worked!
